version: '3'

services:

    postgres:
      image: postgres:14
      container_name: postgres
      volumes:
        - ./postgres:/data/postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_MULTIPLE_DATABASES=internet-shop
        - PGDATA=/data/postgres
      ports:
        - 5432:5432
      restart: always

    pgadmin4:
      container_name: pgadmin4
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
      links:
        - postgres

    minio:
      image: bitnami/minio
      container_name: minio
      restart: always
      ports:
        - "9000:9000"
        - "9001:9001"
      volumes:
        - ./minio/data:/minio/data
      environment:
        - MINIO_ROOT_USER=minio_root
        - MINIO_ROOT_PASSWORD=minio_root
        - MINIO_DEFAULT_BUCKETS=test
        - MINIO_SERVER_ACCESS_KEY=minio
        - MINIO_SERVER_SECRET_KEY=minio

    zookeeper:
      image: 'confluentinc/cp-zookeeper:latest'
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "22181:2181"

    kafka:
      container_name: kafka
      image: 'confluentinc/cp-kafka:latest'
      ports:
        - "29092:29092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CREATE_TOPICS: "santa-mail-topic,santa-present-topic"
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      depends_on:
        - zookeeper
      restart: always